import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import s from "@/styles/Home.module.scss";
import { Container, Row, Col } from "react-bootstrap";
import ButtonUi from "@/components/button";
import BtnDown from "../../public/BtnDown.png";
import CardHomepage from "@/components/CardHomePage";
import Card1 from "../../public/user_3.png";
import pillars from "../../public/Pillars.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={s.main}>
        <div
          className={`d-flex flex-column align-items-start justify-content-center pb-5 ${s.hero}`}
        >
          <Container>
            <Row>
              <Col xs={12}>
                <div className={`d-flex flex-column  ${s.hero__content}`}>
                  <h1>GIVE YOUR OLD PARTS</h1>
                  <p className={s.hero__big}>A NEW LIFE</p>
                  <p className={`mt-3 ${s.hero__content_text}`}>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Vestibulum convallis mi ut velit porttitor placerat. Nulla
                    egestas mattis magna, ut luctus ligula mollis sit amet. Nam
                    vitae leo dignissim, sollicitudin eros in, consequat neque.
                    Suspendisse potenti. Quisque in est mauris. Nullam ut
                    sollicitudin ligula.
                  </p>
                  <div className="d-flex gap-5 mt-5">
                    <ButtonUi> <Link href="/market">START SHOPPING</Link> </ButtonUi>
                    <button
                      style={{
                        background: "transparent",
                        border: "1px solid #FF8F28",
                        color: "#FF8F28",
                        padding: "5px 20px",
                        borderRadius: "25px",
                      }}
                    >
                      <Link href="/sell" style={{
                        textDecoration: "none",
                        color: "#FF8F28",
                      }}> SELL ITEM
                      </Link>
                     
                    </button>
                  </div>
                </div>
              </Col>
            </Row>
          </Container>
        </div>
        <section className={`d-flex gap-5 ${s.card}`} id="home">
          <Container>
            <Row>
              <Col
                xs={12}
                className="d-flex gap-5 justify-content-center flex-wrap"
              >
                <CardHomepage>
                  <Image src={Card1} alt="" />
                  <h1>STEP ONE</h1>
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Vestibulum convallis mi ut velit porttitor placerat. Lorem
                    ipsum dolor sit amet, consectetur adipiscing elit.
                    Vestibulum convallis
                  </p>
                </CardHomepage>
                <CardHomepage>
                  <Image src={Card1} alt="" />
                  <h1>STEP ONE</h1>
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Vestibulum convallis mi ut velit porttitor placerat. Lorem
                    ipsum dolor sit amet, consectetur adipiscing elit.
                    Vestibulum convallis
                  </p>
                </CardHomepage>
                <CardHomepage>
                  <Image src={Card1} alt="" />
                  <h1>STEP ONE</h1>
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Vestibulum convallis mi ut velit porttitor placerat. Lorem
                    ipsum dolor sit amet, consectetur adipiscing elit.
                    Vestibulum convallis
                  </p>
                </CardHomepage>
              </Col>
            </Row>
          </Container>
        </section>
        <section className={s.mission}>
          <Container>
            <Row>
              <Col
                xs={12}
                className="d-flex justify-content-end align-items-center"
              >
                <h1>
                  decreasing student fees and assisting those who are aiming to{" "}
                  <span>learn</span> , <span>grow</span> , and{" "}
                  <span>push limits</span>
                </h1>
              </Col>
            </Row>
          </Container>
        </section>
        <section className={s.pillars}>
          <div className={s.pillars__bg}></div>
          <Container>
            <Row>
              <Col xs={12}>
                <div
                  className={`d-flex flex-column justify-content-between gap-5 ${s.pillars__item}`}
                >
                  <div
                    className={`d-flex justify-content-between flex-wrap ${s.pillars__card}`}
                  >
                    <div className={s.pillars__card_left}>
                      <h1>SUSTAINABILITY</h1>
                      <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                        Vestibulum convallis mi ut velit porttitor placerat.
                        Nulla egestas magna.
                      </p>
                    </div>
                    <div className={s.pillars__card_right}>
                      <h1>COMMUNITY</h1>
                      <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                        Vestibulum convallis mi ut velit porttitor placerat.
                        Nulla egestas magna.
                      </p>
                    </div>
                  </div>
                  <Image
                    className={`${s.pillars__element}`}
                    src={pillars}
                    alt=""
                  />
                  <div
                    className={`d-flex justify-content-between flex-wrap ${s.pillars__card}`}
                  >
                    <div className={s.pillars__card_left}>
                      <h1>INNOVATION</h1>
                      <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                        Vestibulum convallis mi ut velit porttitor placerat.
                        Nulla egestas magna.
                      </p>
                    </div>
                    <div className={s.pillars__card_right}>
                      <h1>GROWTH</h1>
                      <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                        Vestibulum convallis mi ut velit porttitor placerat.
                        Nulla egestas magna.
                      </p>
                    </div>
                  </div>
                </div>
              </Col>
            </Row>
          </Container>
        </section>
      </main>
    </>
  );
}
